builds:
  - binary: dynamo
    goarch: [amd64]
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
nfpms:
  - vendor: dynamo
    homepage: https://github.com/glassechidna/dynamo
    maintainer: Aidan Steele <aidan.steele@glassechidna.com.au>
    description: dynamo is a dead-simple CLI for AWS DynamoDB
    formats: [deb]
brews:
  - github:
      owner: glassechidna
      name: homebrew-taps
    commit_author:
      name: Aidan Steele
      email: aidan.steele@glassechidna.com.au
    homepage: https://github.com/glassechidna/dynamo
    description: dynamo is a dead-simple CLI for AWS DynamoDB
scoop:
  bucket:
    owner: glassechidna
    name: scoop-bucket
  commit_author:
    name: Aidan Steele
    email: aidan.steele@glassechidna.com.au
  homepage: https://github.com/glassechidna/dynamo
  description: dynamo is a dead-simple CLI for AWS DynamoDB
  license: MIT
